Feat/dnsdid did revocation
Open-Attestation/oa-verify pull request #159
Opened 2021-02-11 02:16 UTC by cavacado

context: https://www.pivotaltracker.com/story/show/176199971
this PR does the following:
1. adds a new generating function in `generate.v3` scripts for these two types of files (1. signed and **not** revoked from a document store; 2. signed and **revoked** from a document store) for the file variants DID, and DNS-DID:
2. adds the newly generated files for v2 and v3
3. modifies `didSignedDocumentStatus` file to introduce support for revocation for v2 and v3 DID / DNS-DID documents
4. adds/updates unit test for didSignedDocumentStatus
5. adds/updates integration tests for v2 and v3 files.
6. and some misc refactoring here and there

2021-02-16 07:16 UTC, yehjxraymond commented on scripts/generate.v3.ts
> +  info(`${logMessage}`);
Wondering why you parameterized this. There is a coupling in between the two function in which the caller knows that the log message will be logged as is at the top.

2021-02-16 08:00 UTC, yehjxraymond requested changes
Need to check intermediate hashes when checking for revocation of a document.

2021-02-16 08:22 UTC, cavacado commented on src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.ts
> +        });
i have no idea why I left this out, must have copied something wrongly. 😓

2021-02-16 08:22 UTC, cavacado commented on src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.ts
>        "MISSING_REVOCATION"
sure

2021-02-16 08:23 UTC, cavacado commented on src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.ts
> +    metaData.proof.revocation.location ?? ""
yup will do this.

2021-02-17 01:27 UTC, cavacado commented on src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.test.ts
> +    it("should throw an unrecognized revocation type error when revocation is not set to NONE || REVOCATION_STORE (for now)", async () => {
👌

2021-02-17 01:27 UTC, cavacado commented on src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.test.ts
> +    it("should throw an unrecognized revocation type error when revocation is not set to NONE || REVOCATION_STORE (for now)", async () => {
👌

2021-02-17 02:25 UTC, cavacado commented
@yehjxraymond have done the requested changes and added a check for a null revocation location (else throw) if `REVOCATION_STORE` is used

2021-02-17 03:06 UTC, yehjxraymond approved these changes
lgtm

2021-02-17 03:06 UTC, yehjxraymond commented on src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.ts
> +  const getRevocationStatus = async (docType: v3.RevocationType, location: string | undefined) => {
```suggestion
  const getRevocationStatus = async (docType: v3.RevocationType, location?: string) => {
```

Hmm i think we use `?` most of the time right?

2021-02-17 03:13 UTC, merged

2021-03-02 02:31 UTC, john-dot-oa commented
:tada: This PR is included in version 7.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@govtechsg/oa-verify/v/7.2.0)
- [GitHub release](https://github.com/Open-Attestation/oa-verify/releases/tag/v7.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: